package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.nsu.fit.services.rest.RestClient;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.nsu.fit.services.rest.data.TopUpBalancePojo;
import org.nsu.fit.shared.JsonMapper;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertThrows;

@Feature("Customer top up balance")
public class CustomerTopUpNegativeBalanceTest {

    private static final RestClient restClient = new RestClient();

    private static AccountTokenPojo adminToken;

    private AccountTokenPojo customerToken;


    @BeforeClass
    public static void setup() {
        adminToken = restClient.authenticate("admin", "setup");
    }

    @Test(description = "Top up customer's balance with negative sum")
    @Severity(SeverityLevel.BLOCKER)
    public void topUpBalanceWithNegativeSum() {
        CustomerPojo customer = restClient.createAutoGeneratedCustomer(adminToken);
        customerToken = restClient.authenticate(customer.login, customer.pass);

        TopUpBalancePojo topUpBalancePojo = new TopUpBalancePojo();
        topUpBalancePojo.customerId = customer.id;
        topUpBalancePojo.money = -1000;

        String path = "customers/top_up_balance";
        assertThrows(Exception.class,
                () -> restClient.post(path, JsonMapper.toJson(topUpBalancePojo, true) , Void.class, customerToken));;
    }

}
