package org.nsu.fit.tests.api;

import io.qameta.allure.Feature;
import io.qameta.allure.Severity;
import io.qameta.allure.SeverityLevel;
import org.nsu.fit.services.rest.RestClient;
import org.nsu.fit.services.rest.data.AccountTokenPojo;
import org.nsu.fit.services.rest.data.CustomerPojo;
import org.nsu.fit.services.rest.data.TopUpBalancePojo;
import org.nsu.fit.shared.JsonMapper;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import static org.testng.Assert.assertEquals;
import static org.testng.Assert.assertFalse;
import static org.testng.Assert.assertThrows;

@Feature("Customer top up balance")
public class CustomerTopUpPositiveBalanceTest {

    private static final int BALANCE = 1000;

    private static final RestClient restClient = new RestClient();

    private static AccountTokenPojo adminToken;

    private AccountTokenPojo customerToken;


    @BeforeClass
    public static void setup() {
        adminToken = restClient.authenticate("admin", "setup");
    }

    @Test(description = "Top up customer's balance with positive sum")
    @Severity(SeverityLevel.BLOCKER)
    public void topUpBalanceWithPositiveSum() {
        CustomerPojo customer = restClient.createAutoGeneratedCustomer(adminToken);
        customerToken = restClient.authenticate(customer.login, customer.pass);

        TopUpBalancePojo topUpBalancePojo = new TopUpBalancePojo();
        topUpBalancePojo.customerId = customer.id;
        topUpBalancePojo.money = BALANCE;

        String path = "customers/top_up_balance";
        restClient.post(path, JsonMapper.toJson(topUpBalancePojo, true) , Void.class, customerToken);
    }


    @Test(description = "Check that the balance is increased", dependsOnMethods = "topUpBalanceWithPositiveSum")
    @Severity(SeverityLevel.BLOCKER)
    public void checkBalance() {
        CustomerPojo customerProfile = restClient.get("/me", CustomerPojo.class, customerToken, null);

        assertEquals(customerProfile.balance, BALANCE);
    }

}
